/**
 * This file is generated by generate-i18n.mjs
 * Do not edit this file directly
 */
import type enMessage from '../locales/en/messages.json';
import type plMessage from '../locales/pl/messages.json';

export type MessageKey = keyof typeof enMessage & keyof typeof plMessage;

export type DevLocale = 'en' | 'pl';
